version: '3'

services:
  rmq:
    image: rabbitmq:3.13-rc-management-alpine
    restart: "no"
    hostname: amqp
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    ports:
      - ${RMQ_PORT_WEB}:15672
